### ISSUE TITLE
Trust namespace must be equals to deployment namespace

### ISSUE THREAD

**Issue by Delorien84** [cert-manager/trust#16]
Hello,
 I want to install this application to different namespace then `app.trust.namespace` but I got error about not sufficient permission to create leader election lock. My use case is to install `trust` application several times in `cert-manager` namespace but to point to different `trust namespace`.

The problem is caused by https://github.com/cert-manager/trust/blob/main/deploy/charts/trust/templates/role.yaml that creates permission in deployment namespace not in `trust namespace` causing application does not have sufficient permission to create leader election lock and to watch secrets in `trust namespace`

**Comment by JoshVanL** [comment]
Thanks @Delorien84, I'll open up a PR shorty.

/assign
