### ISSUE TITLE
Java Key/trust Store support

### ISSUE THREAD

**Issue by SpectralHiss** [cert-manager/trust#53]
We have the following use case:

Service A needs to talk to another service B within the same cluster, both are Java applications.
We are attempting to terminate SSL traffic at the pod level, which means loading the cryptomaterial at the Java runtime level.
We have used cert-manager to issue to server certificate and it has been loaded through the newly released Java Key Store secret output format in cert-manager 1.8+.

In order to establish trust across the services, we are making use of the trust project to use an already created Bundle object that contains the internal CA used for ingress.
However it turns out the trust bundle needs to also be loaded as a Java Keystore file, *this is an assumption relayed from the customer and should be 100% confirmed first*.

This is what this issue is trying to have trust Bundle have different output formats matching the cert-manager project with specifically the Java trust bundle store format as a priority.

It would be also nice if there was a way to get roots automatically into Bundle objects tracking a certain issuer, but this is a [separate issue](https://github.com/cert-manager/trust/issues/54) and not essential to this problem.

**Comment by erikgb** [comment]
Duplicate of #17, I think.

**Comment by SpectralHiss** [comment]
yes absolutely it is, closing.
good eye, thanks @erikgb !
